// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6r1DAT7q1A1YEKJgpU9OmH8AVTRO37gs',
    appId: '1:724630837125:web:0082f6cad2922ebc9896ec',
    messagingSenderId: '724630837125',
    projectId: 'appfriends-83192',
    authDomain: 'appfriends-83192.firebaseapp.com',
    storageBucket: 'appfriends-83192.firebasestorage.app',
    measurementId: 'G-HF2QQBK78P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvqmM1XywqnEwGAFjpO9rYjL89S25i1M',
    appId: '1:724630837125:android:f33cba9f808911f59896ec',
    messagingSenderId: '724630837125',
    projectId: 'appfriends-83192',
    storageBucket: 'appfriends-83192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjuDLkm6CH00WGzCQJ8eusrBtk9AhvGHY',
    appId: '1:724630837125:ios:0cbfe3644ee258a09896ec',
    messagingSenderId: '724630837125',
    projectId: 'appfriends-83192',
    storageBucket: 'appfriends-83192.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjuDLkm6CH00WGzCQJ8eusrBtk9AhvGHY',
    appId: '1:724630837125:ios:0cbfe3644ee258a09896ec',
    messagingSenderId: '724630837125',
    projectId: 'appfriends-83192',
    storageBucket: 'appfriends-83192.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6r1DAT7q1A1YEKJgpU9OmH8AVTRO37gs',
    appId: '1:724630837125:web:50d6f8d5f020467d9896ec',
    messagingSenderId: '724630837125',
    projectId: 'appfriends-83192',
    authDomain: 'appfriends-83192.firebaseapp.com',
    storageBucket: 'appfriends-83192.firebasestorage.app',
    measurementId: 'G-1ZEKF7F7JX',
  );

}








